version: '3.7'

services:
  candy_db:
    container_name: candy_db
    image: postgres:15.2-alpine3.17
    restart: always
    command:
      - "postgres"
      - "-c"
      - "port=5444"

    ports:
      - "5444:5444"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER

  candy_bot:
    container_name: candy_bot
    build: .
    restart: always
    ports:
      - "8080:8080"

    depends_on:
      - candy_db


